# Generated by Django 4.0.5 on 2022-06-19 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.ForeignKey(null=b'I00\n', on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.location'),
        ),
    ]
