# Generated by Django 4.0.5 on 2022-06-20 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0004_alter_business_neighbourhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='neighbourhood', to='neighbourhood.neighbourhood'),
        ),
    ]
