# Generated by Django 4.0.5 on 2022-06-20 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0005_alter_profile_neighbourhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='neighbourhood',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.neighbourhood'),
        ),
    ]
