# Generated by Django 4.0.5 on 2022-06-20 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0006_alter_post_neighbourhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='neighbourhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.neighbourhood'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='neighbourhood', to='neighbourhood.neighbourhood'),
        ),
    ]
